#!/usr/bin/env node
// Reads opencode theme JSON files in vendor/opencode-themes and emits:
//   - src/styles/themes.generated.css   — DaisyUI @plugin "daisyui/theme" blocks
//   - src/lib/themes.generated.ts       — manifest of { id, name } entries
//
// Each opencode theme produces TWO DaisyUI themes named `${id}-light` and
// `${id}-dark`. The picker selects the id; a separate color-scheme preference
// (system/light/dark) chooses which variant to apply.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const THEMES_DIR = path.join(ROOT, "vendor/opencode-themes");
const CSS_OUT = path.join(ROOT, "src/styles/themes.generated.css");
const TS_OUT = path.join(ROOT, "src/lib/themes.generated.ts");

const SHARED_TOKENS = {
  "--radius-selector": "0.5rem",
  "--radius-field": "0.5rem",
  "--radius-box": "0.75rem",
  "--size-selector": "0.25rem",
  "--size-field": "0.25rem",
  "--border": "1px",
  "--depth": "0",
  "--noise": "0",
};

function hexToRgb(hex) {
  let h = String(hex).replace("#", "").trim();
  if (h.length === 3)
    h = h
      .split("")
      .map((c) => c + c)
      .join("");
  if (h.length !== 6) throw new Error(`Bad hex: ${hex}`);
  const n = parseInt(h, 16);
  return { r: (n >> 16) & 0xff, g: (n >> 8) & 0xff, b: n & 0xff };
}

function rgbToHex({ r, g, b }) {
  const c = (v) =>
    Math.round(Math.max(0, Math.min(255, v)))
      .toString(16)
      .padStart(2, "0");
  return `#${c(r)}${c(g)}${c(b)}`;
}

// Linear sRGB mix. Ratio 0 → all A, 1 → all B.
function mix(hexA, hexB, ratio) {
  const a = hexToRgb(hexA);
  const b = hexToRgb(hexB);
  return rgbToHex({
    r: a.r * (1 - ratio) + b.r * ratio,
    g: a.g * (1 - ratio) + b.g * ratio,
    b: a.b * (1 - ratio) + b.b * ratio,
  });
}

function relativeLuminance(hex) {
  const { r, g, b } = hexToRgb(hex);
  const lin = (c) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}

// Pick a readable foreground for the given background.
function contrastFor(hex) {
  return relativeLuminance(hex) > 0.5 ? "#0a0a0a" : "#ffffff";
}

function buildVariant(theme, mode) {
  const variant = theme[mode];
  if (!variant?.palette) return null;
  const p = variant.palette;
  const isLight = mode === "light";
  const neutral = p.neutral;
  const ink = p.ink;

  const accent = p.accent ?? p.interactive ?? p.primary;
  const secondary = p.interactive ?? p.accent ?? p.info ?? p.primary;

  return {
    name: `${theme.id}-${mode}`,
    colorScheme: mode,
    tokens: {
      "--color-base-100": neutral,
      "--color-base-200": mix(neutral, ink, isLight ? 0.04 : 0.06),
      "--color-base-300": mix(neutral, ink, isLight ? 0.1 : 0.13),
      "--color-base-content": ink,
      "--color-primary": p.primary,
      "--color-primary-content": contrastFor(p.primary),
      "--color-secondary": secondary,
      "--color-secondary-content": contrastFor(secondary),
      "--color-accent": accent,
      "--color-accent-content": contrastFor(accent),
      "--color-neutral": ink,
      "--color-neutral-content": neutral,
      "--color-info": p.info,
      "--color-info-content": contrastFor(p.info),
      "--color-success": p.success,
      "--color-success-content": contrastFor(p.success),
      "--color-warning": p.warning,
      "--color-warning-content": contrastFor(p.warning),
      "--color-error": p.error,
      "--color-error-content": contrastFor(p.error),
      ...SHARED_TOKENS,
    },
  };
}

function emitBlock(variant) {
  const lines = Object.entries(variant.tokens)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");
  return `@plugin "daisyui/theme" {
  name: "${variant.name}";
  color-scheme: ${variant.colorScheme};
${lines}
}`;
}

function main() {
  const files = fs
    .readdirSync(THEMES_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort();

  const blocks = [];
  const manifest = [];

  for (const file of files) {
    const raw = fs.readFileSync(path.join(THEMES_DIR, file), "utf8");
    const theme = JSON.parse(raw);
    const light = buildVariant(theme, "light");
    const dark = buildVariant(theme, "dark");
    if (!light || !dark) {
      console.warn(`skipping ${theme.id}: missing light or dark variant`);
      continue;
    }
    blocks.push(`/* ${theme.name} (${theme.id}) */`);
    blocks.push(emitBlock(light));
    blocks.push(emitBlock(dark));
    blocks.push("");
    manifest.push({ id: theme.id, name: theme.name });
  }

  fs.mkdirSync(path.dirname(CSS_OUT), { recursive: true });
  fs.writeFileSync(
    CSS_OUT,
    `/* Generated by scripts/generate-themes.mjs — do not edit by hand. */\n\n${blocks.join("\n")}`,
  );

  const manifestJson = JSON.stringify(manifest, null, 2);
  fs.writeFileSync(
    TS_OUT,
    `// Generated by scripts/generate-themes.mjs — do not edit by hand.\n\nexport type ThemeManifestEntry = { id: string; name: string };\n\nexport const GENERATED_THEMES: readonly ThemeManifestEntry[] = ${manifestJson} as const;\n`,
  );

  console.log(
    `Generated ${manifest.length} themes → ${path.relative(ROOT, CSS_OUT)}, ${path.relative(ROOT, TS_OUT)}`,
  );
}

main();
